name: test_server_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  cached_network_image: ^3.4.1
  country_pickers: ^3.0.1
  equatable: ^2.0.5
  file_picker: ^8.1.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_contacts: ^1.1.9+2
  flutter_pin_code_fields: ^2.2.0
  fluttertoast: ^8.2.8
  get_it: ^8.0.2
  giphy_picker: ^3.0.2
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  socket_io_client: ^3.0.1
  video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/bg_image.png
    - assets/meta.png
    - assets/profile_default.png
    - assets/whats_app_logo.png
    - assets/whatsapp_bg_image.png
